#
# Copyright (C) 2014 Marco Stipek <ms-safe@it-agenten.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: clone freetz repo
  subversion: repo={{ freetz_svn_url }} dest=freetz
  sudo: no
- name: link images directory to shared vagrant directory
  file: src=/vagrant/images dest=freetz/images state=link
  sudo: no
- name: On login, symlink /vagrant/config to ~/freetz/config if it does not exist
  lineinfile: dest=.profile state=present insertafter=EOF line='if [ ! -L ~/freetz/.config ]; then mv ~/freetz/.config ~/freetz/.config.old; ln -s /vagrant/config ~/freetz/.config; fi'
  sudo: no
- name: On logout, copy ~/freetz/config to /vagrant/config if it is newer
  lineinfile: dest=.bash_logout state=present insertafter=EOF line='if [ ! -L ~/freetz/.config ]; then cp -u ~/freetz/.config /vagrant/config; fi'
  sudo: no
