#
# Copyright (C) 2014 Marco Stipek <ms-safe@it-agenten.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---


- name: General | Install required packages.
  action: apt pkg={{ item }} state=latest
  with_items:
    - ack-grep
    - ack-grep
    - autoconf
    - automake
    - bison
    - build-essential
    - bzip2
    - di
    - fastjar
    - flex
    - gawk
    - gcc-multilib
    - gettext
    - git-core
    - htop
    - imagemagick
    - iotop
    - jam
    - lib32ncurses5-dev
    - libacl1-dev
    - libc6-dev-i386
    - libcap-dev
    - libncurses5-dev
    - libreadline6-dev
    - libstring-crc32-perl
    - libtool
    - libtool-bin
    - libusb-dev
    - mktemp
    - ngrep
    - openssh-server
    - patch
    - patchutils
    - perl
    - pkg-config
    - python
    - python-apt
    - python-pip
    - python-pycurl
    - python-software-properties
    - realpath
    - ruby
    - subversion
    - texinfo
    - tmux
    - tofrodos
    - unzip
    - vim
    - wget
    - xz-utils
    - zlib1g-dev
    - zsh
